name: Danger

on: [pull_request]

jobs:
  build:
    name: Run Danger
    runs-on: macOS-latest
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator12.2
            destination: platform=iOS Simulator,name=iPhone XS,OS=12.2
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v1
    - name: Install Bundler
      run: | 
        gem install bundler
        bundle install
    - name: Install Carthage
      run: | 
        brew install carthage
        carthage update
    - name: Test Automation
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        PROJECT: CleanRepository.xcodeproj
        SCHEME: CleanRepository
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
    - name: Test Coverage & Lint
      run: |
        echo "Running Danger..."
        bundle exec danger --fail-on-errors=true
        success="1"
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
